# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_BASICAUTH=false

  test-react-app:
    build: ./test-react-backend
    ports:
      - 3030:3030
    depends_on:
      - mongo
    environment:
      - REACT_APP_PORT=3030
      - REACT_APP_MONGODB_URL=mongodb://root:example@mongo:27017/test-react-mongo
      - VITE_REACT_APP_API_URL=http://localhost:3030/api
